### ISSUE TITLE
Discussion: Tests separate from code or alongside?

### ISSUE THREAD

**Issue by mrpudn** [mrpudn/wtf#27]
Just opening this up for general discussion:

Should the tests live separate from the code?
https://docs.pytest.org/en/latest/goodpractices.html#tests-outside-application-code
```
setup.py
mypkg/
    __init__.py
    app.py
    view.py
tests/
    test_app.py
    test_view.py
    ...
```

Or, should they life alongside the code?
https://docs.pytest.org/en/latest/goodpractices.html#tests-as-part-of-application-code
```
setup.py
mypkg/
    __init__.py
    app.py
    view.py
    test/
        __init__.py
        test_app.py
        test_view.py
        ...
```

I can see pros and cons to both approaches, but I thought we could open it up for discussion and try to establish a convention going forward.

I've traditionally kept the tests separate from the application code in most of my projects, but I've experimented in the past with keeping them alongside the code they test, and although different, it was very convenient, particularly when a project grows large, and it becomes awkward to navigate deep directory structures to find tests or their respective application code.

Any preference @njgrisafi? We can leave this discussion open and see how it goes.

**Comment by njgrisafi** [comment]
This is a great topic and new to me. I've personally never worked on a project that had the test alongside the application code but I really like the idea of having the tests in close proximity to the modules.

Like you said, I often get lost in the `tests/` directory and find it difficult to keep in sync with the folder and tests that live there. Mainly because when the tests are isolated from the application you don't find yourself navigating through the directory as frequently.

Having the tests with the application code will increase the exposure to all test modules and as developers move around module to module they will be able to see the tests contained inside. Also, when new members join this project, the consistent pattern will bring as ease of project navigation and strengthen the requirement of having tests for each module.

It also allows the root of the project simple and more compact overall. 

If we plan on maintaining high test coverage - I believe having tests apart of the application code would help increase that percentage.

One thing that would be confusing is how to build the distribution folder for the application. Would the test be included with the release application? Or how would we go to exclude them? Do we plan on testing the UI and would the UI folder follow the same pattern?

Those are the only issues I can think of at the time and I'm sure that the solution to my questions are fairly simple :).

That being said, I'm all for any approach but I would like to experiment with having the apart of the application code.

**Comment by mrpudn** [comment]
> Like you said, I often get lost in the tests/ directory and find it difficult to keep in sync with the folder and tests that live there. Mainly because when the tests are isolated from the application code you don't find yourself navigating through the directory as frequently.

Exactly. This is the biggest advantage, imo. I think I'm convinced - we can start migrating them to live alongside the codebase. Would you like to work on this, @njgrisafi?

You know, another thing I just realized is that this will simplify the imports in the test files.

Instead of this:
```py
import foo.bar.baz.where.are.you
```

You'll just be able to do:
```py
import .you
```

(Since your test module is in the same directory as your application module)

> One thing that would be confusing is how to build the distribution folder for the application. Would the test be included with the release application?

Good point - I think you can ignore file patterns when you build it for distribution, but I think it should be ok to just keep the tests in there. I don't think they'll hurt anything.

The only inconvenient thing I can think of is managing common test code (particularly test fixtures), but I'm not sure that's a major concern. Most test fixtures that I can think of would probably be set up a bit differently per test module anyway.

> Do we plan on testing the UI and would the UI folder follow the same pattern?

These should work the same exact way for the python testing for the Flask portion of the UI (handling routing and what not). We can also use this kind of test structure for our JavaScript tests, so we'll be able to keep it consistent.

**Comment by njgrisafi** [comment]
@mrpudn Awesome - I'll take on the test migration. I'll submit an issue for this.

**Comment by mrpudn** [comment]
Closing this one
